from __future__ import annotations
from typing import Protocol, Callable, TYPE_CHECKING
from src.domain.events.base import DomainEvent

if TYPE_CHECKING:
    from src.domain.battle_state import BattleState

class IEventBus(Protocol):
    def publish(self, event: DomainEvent) -> None: ...
    def subscribe(self, event_type: type, handler: Callable) -> None: ...
    def unsubscribe(self, event_type: type, handler: Callable) -> None: ...

class IBattleRepository(Protocol):
    def get(self) -> BattleState: ...
    def save(self, state: BattleState) -> None: ...
