from __future__ import annotations
from typing import Protocol, Callable, TYPE_CHECKING
from src.domain.events.base import DomainEvent

if TYPE_CHECKING:
    from src.domain.battle_state import BattleState
    from src.domain.entities.card import Card
    from src.domain.run_state import RunState

class IEventBus(Protocol):
    def publish(self, event: DomainEvent) -> None: ...
    def subscribe(self, event_type: type, handler: Callable) -> None: ...
    def unsubscribe(self, event_type: type, handler: Callable) -> None: ...

class IBattleRepository(Protocol):
    def get(self) -> BattleState: ...
    def save(self, state: BattleState) -> None: ...

class ICardRepository(Protocol):
    def get_starting_deck(self) -> list[Card]: ...
    def get_random_cards(self, n: int) -> list[Card]: ...

class IRunRepository(Protocol):
    def get(self) -> RunState: ...
    def save(self, state: RunState) -> None: ...
    def has_active_run(self) -> bool: ...
